name: snowplow_tracker
description: A package for tracking Snowplow events in Flutter apps
version: 0.5.0
homepage: https://github.com/snowplow-incubator/snowplow-flutter-tracker
repository: https://github.com/snowplow-incubator/snowplow-flutter-tracker

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.7.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  http: ^1.2.0

flutter:
  plugin:
    platforms:
      android:
        package: com.snowplowanalytics.snowplow_tracker
        pluginClass: SnowplowTrackerPlugin
      ios:
        pluginClass: SnowplowTrackerPlugin
      web:
        pluginClass: SnowplowTrackerPluginWeb
        fileName: snowplow_tracker_plugin_web.dart
